AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestructura completa'
Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/mybucket/templates/vpc.yaml'

  SubnetsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/mybucket/templates/subnets.yaml'

  InstancesStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/mybucket/templates/ec2-instances.yaml'

  LoadBalancerStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/mybucket/templates/load-balancer.yaml'
